Inspecciones repository1
gomac-un/app_inspecciones pull request #21
Opened 2021-10-03 01:57 UTC by jcorreapa

Avance en llenado_Dao, metodos para guardar y cargar inspecciones

2021-10-03 03:23 UTC, victorcatn requested changes
Lo veo bonito todo, excepto porque no se está considerando el orden de los bloques que está en la tabla bloques, entonces la inspeccion se carga desordenada

2021-10-03 23:39 UTC, jcorreapa commented
> Lo veo bonito todo, excepto porque no se está considerando el orden de los bloques que está en la tabla bloques, entonces la inspeccion se carga desordenada

No había tenido en cuenta eso, pero añadí un atributo nOrden a la clase Bloque para que al momento de cargarlos el repositorio los pueda ordenar por ese atributo

2021-10-04 21:28 UTC, victorcatn requested changes
estos deberían ser los ultimos cambios antes de hacer el merge, el cual debe ser lo mas pronto posible para no diverger mucho.
El cambio del nOrden es opcional, si lo ves muy dificil lo puedes dejar así.

2021-10-04 21:28 UTC, victorcatn commented on lib/infrastructure/daos/llenado_dao.dart
> +    return null;
Usar una condición de guarda para que quede mas bonito
```suggestion
    if (res == null) return null;
    return bl_dom.RespuestaNumerica(getMetaRespuesta(res),
          respuestaNumerica: res.valor);
    
```

2021-10-04 21:28 UTC, victorcatn commented on lib/infrastructure/daos/llenado_dao.dart
> +  Future<List<bl_dom.PreguntaNumerica>> getPreguntaNumerica(int cuestionarioId,
```suggestion
  Future<List<bl_dom.PreguntaNumerica>> getPreguntasNumericas(int cuestionarioId,
```

2021-10-04 21:28 UTC, victorcatn commented on lib/infrastructure/daos/llenado_dao.dart
> +    if (res.isEmpty) return [];
No es necesario porque `res.isEmpty` si y solo si `res == []`
```suggestion
```

2021-10-04 21:57 UTC, jcorreapa commented on lib/features/llenado_inspecciones/infrastructure/inspecciones_repository.dart
> +            .firstWhere((element) => element.index == inspeccion.estado.index),
El enum de inspección está definido en el dominio y el estado que se le debe enviar a moor.Inspeccion está definido en core, entonces salía error. El problema con esto es que ambos deben ser iguales y estar en el mismo orden siempre.

2021-10-04 22:51 UTC, victorcatn commented on lib/features/llenado_inspecciones/infrastructure/inspecciones_repository.dart
> +            .firstWhere((element) => element.index == inspeccion.estado.index),
Entiendo, entonces debemos integrarlo en uno solo, creo que podemos dejar solo el de dominio

2021-10-10 06:27 UTC, merged